pipeline
{
	agent any
		{
		stages
			{
			stage('clean stage')
				{
				steps{
					withMaven(maven : 'Maven-3.8.5')
					sh 'mvn clean'
					}
				}
			stage('compile stage')
                                {
                                steps{  
                                        withMaven(maven : 'Maven-3.8.5')
                                        sh 'mvn compile'
                                        }
                                }
			 stage('build stage')
                                {
                                steps{
                                        withMaven(maven : 'Maven-3.8.5')
                                        sh 'mvn package'
                                        }
                                }

			}
		}
}
